# Generated by Django 4.1.6 on 2023-10-17 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_student_debt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.IntegerField(blank=True, choices=[(1, 'active'), (2, 'in_group'), (3, 'leave'), (4, 'graduated'), (5, 'passive')], default=1, null=True),
        ),
    ]
