# Generated by Django 4.1.6 on 2023-10-17 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_student_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.IntegerField(choices=[(1, 'active'), (2, 'in_group'), (3, 'leave'), (4, 'graduated'), (5, 'passive')], default=1),
        ),
    ]
